"""
Stage 0 — Shared structural layer for the deterministic IntelliAudit gate.

This module turns the raw AuditBench inputs (a ``[row n]`` table string and a
free-text transaction narrative) into structured objects that Stage 0A
(arithmetic verifier) and Stage 0B (equation checker) consume.

It deliberately does NOT classify any error on its own — it only:
  * parses the modified financial statement into ordered, typed rows
    (header / leaf / subtotal) as a pandas DataFrame,
  * parses the transaction narrative into a per-row "correct value" oracle
    keyed by both the original row index and the (normalized) row label,
  * exposes a small set of matching helpers used by both stages, and
  * combines the two stages' findings into a single deterministic verdict.

Design notes / data caveats (verified against the real dataset):
  * Transaction `[contributing to row N]` indices refer to the *original*
    (pre-injection) numbering. A Missing/Redundant/Misclassification error
    shifts the modified table's indices, so label/index matching is guarded.
  * The `[Explanation: $X = $a + $b]` RHS is LLM-generated and occasionally
    drops a term or has a typo; the **LHS ($X)** is the reliable per-row value,
    so we always read the LHS, never re-derive from the RHS.
  * Values may be negative via parentheses ($(214)) or a leading minus.

Reuses `parser.parse_table` / `parser.parse_numeric_value`.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional

import pandas as pd

from parser import parse_table, parse_numeric_value

# Comparison tolerance. Statement values are integers (in thousands/millions);
# 0.5 makes the checks exact for integers while tolerating float artifacts.
TOL = 0.5


# ── Label normalization ───────────────────────────────────────────────────────
def norm_label(s: str) -> str:
    """Lowercase, drop punctuation, collapse whitespace. Curly→straight quote."""
    s = (s or "").replace("\u2019", "'")
    s = re.sub(r"[^a-z0-9]+", " ", s.lower())
    return " ".join(s.split()).strip()


def core_label(norm: str) -> str:
    """Strip a trailing ' - <qualifier>' the transaction text sometimes adds,
    e.g. 'marketable securities non current' → 'marketable securities'.
    Operates on an already-normalized label."""
    for qual in (" non current", " current", " cost"):
        if norm.endswith(qual):
            return norm[: -len(qual)].strip()
    return norm


_NAMED_SUBTOTAL_KEYS = (
    "gross margin",
    "gross profit",
    "operating income",
    "operating loss",
    "income before provision",
    "income before income tax",
    "net income",
    "net loss",
    "cash generated by",
    "cash used in",
    "net cash provided",
    "net cash used",
    "increase decrease in cash",
    "net increase decrease in cash",
    "net change in cash",
)


def _is_subtotal_label(norm: str) -> bool:
    if norm.startswith("total "):
        return True
    return any(k in norm for k in _NAMED_SUBTOTAL_KEYS)


def approx_eq(a: Optional[float], b: Optional[float], tol: float = TOL) -> bool:
    return a is not None and b is not None and abs(a - b) <= tol


REL_TOL = 0.005  # 0.5% — absorbs rounding noise in LLM-written explanations


def values_match(a: Optional[float], b: Optional[float], tol: float = TOL) -> bool:
    """Equal up to sign and a small relative tolerance. The transaction
    narratives routinely state magnitudes ('$160') for rows the statement shows
    signed ('($160)'), so a sign-only difference must NOT be read as a value
    change; likewise a sub-percent rounding gap is narration noise, not an error.
    Injected numerical errors move values far more than 0.5%."""
    if a is None or b is None:
        return False
    rel = REL_TOL * max(abs(a), abs(b))
    bound = max(tol, rel)
    return abs(a - b) <= bound or abs(abs(a) - abs(b)) <= bound


_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)


def strip_noise(s: Optional[str]) -> str:
    """Remove HTML-comment markers the error injector leaves behind (e.g.
    '$22,118 <!-- An incorrect value entered deliberately -->') and wrapping
    quotes/asterisks, which otherwise corrupt label/value parsing."""
    if s is None:
        return ""
    return _HTML_COMMENT_RE.sub("", s).replace('"', "").replace("*", "").strip()


def clean_value(raw: Optional[str]) -> Optional[float]:
    """parse_numeric_value after stripping injector noise and wrapping quotes,
    which would otherwise fail to parse and silently demote a real leaf row to a
    value-less 'header'."""
    if raw is None:
        return None
    return parse_numeric_value(strip_noise(raw))


# ── Structured table ──────────────────────────────────────────────────────────
@dataclass
class Row:
    idx: int
    label: str
    norm: str
    core: str
    value: Optional[float]
    kind: str  # 'header' | 'leaf' | 'subtotal'


def build_table(table_str: str) -> pd.DataFrame:
    """Parse a `[row n]` table into an ordered DataFrame of typed rows."""
    parsed = parse_table(table_str)
    rows: List[Row] = []
    for idx in sorted(parsed):
        label = strip_noise(parsed[idx]["label"])
        value = clean_value(parsed[idx]["value"])
        nlab = norm_label(label)
        if value is None:
            kind = "header"
        elif _is_subtotal_label(nlab):
            kind = "subtotal"
        else:
            kind = "leaf"
        rows.append(Row(idx, label, nlab, core_label(nlab), value, kind))
    return pd.DataFrame([r.__dict__ for r in rows])


def rows_of(df: pd.DataFrame, kind: Optional[str] = None) -> List[Row]:
    out = []
    for _, r in df.iterrows():
        if kind is None or r["kind"] == kind:
            out.append(Row(int(r["idx"]), r["label"], r["norm"], r["core"],
                           (None if pd.isna(r["value"]) else float(r["value"])),
                           r["kind"]))
    return out


def next_subtotal_after(df: pd.DataFrame, idx: int) -> Optional[Row]:
    """First subtotal row appearing at a position after `idx` in the table."""
    for r in rows_of(df):
        if r.idx > idx and r.kind == "subtotal":
            return r
    return None


def subtotal_at_or_after(df: pd.DataFrame, idx: int) -> Optional[Row]:
    """First subtotal row at position >= idx (the subtotal that encloses idx)."""
    for r in rows_of(df):
        if r.idx >= idx and r.kind == "subtotal":
            return r
    return None


def subtotal_expected_map(df: pd.DataFrame, tx: "Transactions") -> Dict[int, Optional[float]]:
    """Map each table subtotal's row index to its transaction-oracle value.

    None of the four error types add or remove a *subtotal* (they touch leaves),
    so the ordered list of subtotals is preserved between the table and the
    transactions. When the two lists are the same length we therefore align them
    positionally — far more robust than label matching, which only succeeds ~64%
    of the time (cash-flow/income-statement aggregate labels vary a lot). When
    the counts differ we fall back to unique-label matching per subtotal."""
    tb = rows_of(df, "subtotal")
    ts = [e for e in tx.entries if e.is_subtotal and e.value is not None]
    out: Dict[int, Optional[float]] = {}
    if tb and len(tb) == len(ts):
        for s, e in zip(tb, ts):
            out[s.idx] = e.value
    else:
        for s in tb:
            out[s.idx] = tx.expected_subtotal(s.core)
    return out


def infer_groups(df: pd.DataFrame) -> Dict[int, List[int]]:
    """Best-effort hierarchy: map each subtotal to the contiguous run of leaf
    rows since the previous subtotal/section header. Grand totals that sum other
    subtotals (no leaves directly under them) get an empty member list and are
    simply skipped by callers. Heuristic — used only for the footing fallback."""
    groups: Dict[int, List[int]] = {}
    pending: List[int] = []
    for r in rows_of(df):
        if r.kind == "header":
            pending = []                       # new section starts fresh
        elif r.kind == "leaf":
            pending.append(r.idx)
        elif r.kind == "subtotal":
            groups[r.idx] = list(pending)
            pending = []
    return groups


# ── Transaction oracle ────────────────────────────────────────────────────────
@dataclass
class TxEntry:
    order: int                 # appearance order in the narrative
    orig_index: Optional[int]  # original row index from [contributing to row N]
    label: str
    norm: str
    core: str
    value: Optional[float]
    is_subtotal: bool


@dataclass
class Transactions:
    entries: List[TxEntry]

    def __post_init__(self):
        self.by_index: Dict[int, TxEntry] = {}
        for e in self.entries:
            if e.orig_index is not None and e.orig_index not in self.by_index:
                self.by_index[e.orig_index] = e

    # core-label → entries (document order)
    def by_core(self, core: str) -> List[TxEntry]:
        return [e for e in self.entries if e.core == core]

    def value_present(self, core: str) -> bool:
        return any(e.core == core for e in self.entries)

    def expected_for_index(self, idx: int) -> Optional[TxEntry]:
        return self.by_index.get(idx)

    def unique_by_core(self, core: str) -> Optional[TxEntry]:
        hits = self.by_core(core)
        return hits[0] if len(hits) == 1 else None

    def next_subtotal_after_orig(self, orig_index: int) -> Optional[TxEntry]:
        cand = [e for e in self.entries
                if e.is_subtotal and e.orig_index is not None and e.orig_index > orig_index]
        cand.sort(key=lambda e: e.orig_index)
        return cand[0] if cand else None

    def expected_subtotal(self, sub_core: str) -> Optional[float]:
        e = self.unique_by_core(sub_core)
        return e.value if (e and e.value is not None) else None


_CONTRIB_RE = re.compile(r"\[contributing to row\s+([^\]]+)\]\s*:?\s*", re.IGNORECASE)
_EXPL_LHS_RE = re.compile(r"\[Explanation:\s*([^=\]]+?)\s*=", re.IGNORECASE)
_FIRST_INT_RE = re.compile(r"\d+")


def _first_index(token: str) -> Optional[int]:
    m = _FIRST_INT_RE.search(token)
    return int(m.group()) if m else None


def build_transactions(tx_str: str) -> Transactions:
    """Split the narrative into `[contributing to row ...]` blocks and read each
    block's row label, inline value, and (preferred) Explanation LHS value."""
    tx_str = tx_str or ""
    marks = list(_CONTRIB_RE.finditer(tx_str))
    entries: List[TxEntry] = []
    for order, m in enumerate(marks):
        start = m.end()
        end = marks[order + 1].start() if order + 1 < len(marks) else len(tx_str)
        block = tx_str[start:end]
        idx_token = m.group(1)
        orig_index = _first_index(idx_token)

        # Header line = text up to first newline; label is before any '|'.
        header = block.split("\n", 1)[0]
        label_part = header.split("|", 1)[0]
        label = strip_noise(label_part.replace("[SEP]", "")).rstrip(":").strip()

        # Preferred value = Explanation LHS; fallback = inline "| $value".
        value: Optional[float] = None
        em = _EXPL_LHS_RE.search(block)
        if em:
            value = clean_value(em.group(1))
        if value is None and "|" in header:
            inline = header.split("|", 1)[1].replace("[SEP]", "").strip()
            value = clean_value(inline)

        nlab = norm_label(label)
        entries.append(TxEntry(order, orig_index, label, nlab, core_label(nlab),
                               value, _is_subtotal_label(nlab)))
    return Transactions(entries)


# ── Findings + combination ────────────────────────────────────────────────────
@dataclass
class Finding:
    error_type: Optional[str] = None       # canonical AuditBench label
    problematic_entry: Optional[int] = None
    correct_value: Optional[float] = None
    stated_value: Optional[float] = None
    source: str = ""                       # '0A' | '0B'
    detail: str = ""


@dataclass
class Stage0AResult:
    flagged: bool = False
    primary: Optional[Finding] = None     # strong: leaf Numerical / Missing Row
    weak: Optional[Finding] = None        # last-resort: subtotal-level tamper
    reconciliation: List[dict] = field(default_factory=list)  # leaf value mismatches
    footing: List[dict] = field(default_factory=list)         # subtotal mismatches
    missing: List[dict] = field(default_factory=list)


@dataclass
class Stage0BResult:
    flagged: bool = False
    primary: Optional[Finding] = None
    equations: List[dict] = field(default_factory=list)
    redundant: List[dict] = field(default_factory=list)
    misclassification: List[dict] = field(default_factory=list)


def combine_findings(a: Stage0AResult, b: Stage0BResult) -> Optional[Finding]:
    """Deterministic verdict, most-specific signal first:
        1. Stage 0A strong (leaf Numerical Error / Missing Row),
        2. Stage 0B (Redundant Row / Misclassification),
        3. Stage 0A weak (a tampered subtotal) — only when there is no structural
           evidence at all, since a redundant/missing/misclassified leaf also
           breaks a subtotal and would otherwise be mislabelled 'Numerical'.
    Abstain (None) if no stage produced a finding."""
    if a.primary is not None:
        return a.primary
    if b.primary is not None:
        return b.primary
    if a.weak is not None and not (b.redundant or b.misclassification or a.missing):
        return a.weak
    return None
